image:
  repository: coderchirag2002/multi-app-client
  tag: latest

minReplicas: 2
maxReplicas: 5

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"
