apiVersion: v1
kind: Pod
metadata:
  name: nginx-server
  labels:
    app.kubernetes.io/component: server
spec:
  initContainers:
    - name: init-server
      image: docker.io/nginx:latest
      command:
        [
          "sh",
          "-c",
          'echo "<html><body>Hello World</body></html>" > /usr/share/nginx/html/index.html',
        ]
      volumeMounts:
        - name: nginx
          mountPath: /usr/share/nginx/html
  containers:
    - name: nginx-server
      image: docker.io/nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nginx
          mountPath: /usr/share/nginx/html
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      startupProbe:
        httpGet:
          path: /
          port: 80
        failureThreshold: 5
        initialDelaySeconds: 10
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /
          port: 80
        failureThreshold: 5
        timeoutSeconds: 10
        periodSeconds: 60
      readinessProbe:
        httpGet:
          path: /
          port: 80
        failureThreshold: 5
        timeoutSeconds: 10
        periodSeconds: 60
  volumes:
    - name: nginx
      emptyDir: {}
