apiVersion: v1
kind: Pod
metadata:
  name: nginx-server
  labels:
    component: server
spec:
  containers:
    - name: nginx-server
      image: docker.io/nginx:latest
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      startupProbe:
        httpGet:
          path: /
          port: 80
        failureThreshold: 5
        initialDelaySeconds: 10
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /
          port: 80
        failureThreshold: 5
        timeoutSeconds: 10
        periodSeconds: 60
      readinessProbe:
        httpGet:
          path: /
          port: 80
        failureThreshold: 5
        timeoutSeconds: 10
        periodSeconds: 60
