apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: mysql
  template:
    metadata:
      labels:
        app.kubernetes.io/component: mysql
    spec:
      volumes:
        - name: {{ .Release.Name }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.ports.containerPort }}
          env:
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.db }}
            - name: MYSQL_ROOT_PASSWORD
              # value: password123
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mysql.passwordSecretName }}
                  key: {{ .Values.mysql.passwordSecretKey }} 
          volumeMounts:
            - name: {{ .Release.Name }}
              mountPath: {{ .Values.mysql.volumeMountPath }}
              subPath: {{ .Values.mysql.volumeSubPath }}
          resources:
{{ toYaml .Values.resources | indent 12 }}