apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: server
spec:
  replicas: 1
  selector:
    matchLabels:
      component: worker
  template:
    metadata:
      labels:
        component: worker
    spec:
      containers:
        - name: worker-container
          image: coderchirag2002/multi-app-worker
          env:
            - name: REDIS_HOST
              value: "redis.redis"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: password123
