apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: server
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server-container
          image: coderchirag2002/multi-app-server
          env:
            - name: REDIS_HOST
              value: redis.redis
            - name: REDIS_PORT
              value: "6379"
            - name: MYSQL_HOST
              value: mysql.mysql
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              value: root
            - name: MYSQL_DATABASE
              value: k8s_setup
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-password
                  key: MYSQL_PASSWORD
          ports:
            - containerPort: 5000
