apiVersion: v1
kind: Pod
metadata:
  name: fib-next-app
  labels:
    component: client
spec:
  containers:
    - name: fib-next-app
      image: coderchirag2002/fib-next-app
      ports:
        - containerPort: 3000
