apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: poc
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: server
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31515
