version: '3'
services:
  mysql:
   image: mysql:latest
   restart: always
   environment:
    MYSQL_ROOT_PASSWORD: password123
    MYSQL_DATABASE: docker_compose_setup
  redis:
    image: redis:latest
    restart: always
  worker:
    depends_on: 
      - redis
    image: 'coderchirag2002/multi-app-worker'
    mem_limit: 512m
    hostname: worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: always
  server:
    depends_on: 
      - mysql
      - redis
    image: 'coderchirag2002/multi-app-server'
    build:
      dockerfile: Dockerfile
      context: ./server
    mem_limit: 512m
    hostname: api
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password123
      - MYSQL_DATABASE=docker_compose_setup
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: always
  client:
    depends_on:
      - server
    image: 'coderchirag2002/multi-app-client'
    mem_limit: 128m
    hostname: client
    restart: always
  nginx:
    depends_on:
      - client
    image: 'coderchirag2002/multi-app-nginx'
    mem_limit: 128m
    hostname: nginx
    ports:
      - '8080:80'
    restart: always
